### ISSUE TITLE
Erro no filtro de consulta livre

### ISSUE THREAD

**Issue by CristianoMCon** [rafwell/laravel-grid#2]
Quando tento filtrar os resultados de forma livre dae dá um erro no sql conforme abaixo:

SQLSTATE[HY000]: General error: 1271 Ilegal combinação de collations para operação 'concat' (SQL: select count(*) as aggregate from (select id as id, descricao as descricao, (case when ativo = 1 then 'Sim' else 'Não' end) as status, created_at as created_at, preco as preco from `produtos`) produtos where CONCAT(COALESCE(id, ''),COALESCE(descricao, ''),COALESCE(status, ''),COALESCE(created_at, ''),COALESCE(preco, '')) like %arroz%)

Vou tentar resolver e posto aqui senão se já conseguiu e poder passar a solução agradeço.

Obs: Show de bola essa package, parabéns!

**Comment by rafwell** [comment]
Oi. Obrigado!

Você está usando SQL Server? Este erro eu já passei com SQL Server, porque estava tentando concatenar campos que possuem collates diferentes. Talvez você esteja fazendo um join em tabelas de outra database através de uma view ou algo assim, foi o meu caso. 

Tente executar a query no seu banco de dados, verá que o erro também será mostrado.

**Comment by CristianoMCon** [comment]
Opa! Então, estou usando MySQL server, por enquanto não criei nenhuma query, estou seguindo a demonstração, aquele query de produtos, bem avançada essa query, curti.
O erro era exatamente esse mesmo, de collation, depois de entender o motivo desse erro e algumas alterações, consegui executar a query direto no banco de dados, o passo seguinte foi corrigir na aplicação, fiz algumas alterações no metodo make e agora esta funfando que é uma blza. Estou fazendo novos testes para confirmar se esta solução esta correta mesmo, quando estiver concluido postarei ela aqui para, caso você ache necessário, incluir no seu projeto.

**Comment by rafwell** [comment]
Blz, manda!

**Comment by rafwell** [comment]
Nenhuma outra ocorrência foi registrada quanto a este bug. Caso o erro persista na versão atual, solicite a reabertura deste issue.
